<?php

declare(strict_types=1);

/**
 * Regenerate database/schema.sql — a single consolidated, committed snapshot of
 * the full database structure (no data). Run after applying migrations:
 *
 *   php database/migrate.php --seed && php database/dump_schema.php
 *
 * The numbered files in database/schema/ remain the source of truth for
 * *applying* changes incrementally; schema.sql is the readable whole-picture
 * reference and a fast path for spinning up a fresh database in one import.
 */

use App\Core\Database;

require dirname(__DIR__) . '/app/bootstrap.php';

$db  = Database::instance();
$pdo = $db->pdo();

$tables = $pdo->query(
    "SELECT table_name FROM information_schema.tables
     WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE'
     ORDER BY table_name"
)->fetchAll(PDO::FETCH_COLUMN);

$out = [];
$out[] = "-- =====================================================================";
$out[] = "-- AgriVault — consolidated database schema (generated)";
$out[] = "--";
$out[] = "-- Generated by database/dump_schema.php from the applied migrations in";
$out[] = "-- database/schema/. Do not edit by hand: change a migration and re-run.";
$out[] = "--";
$out[] = "-- Fresh install in one shot:";
$out[] = "--   mysql -u USER -p DBNAME < database/schema.sql";
$out[] = "--   then: INSERT the database/seed/*.sql files.";
$out[] = "-- =====================================================================";
$out[] = "";
$out[] = "SET FOREIGN_KEY_CHECKS = 0;";
$out[] = "SET NAMES utf8mb4;";
$out[] = "";

foreach ($tables as $table) {
    $row = $pdo->query('SHOW CREATE TABLE ' . $db->quoteIdent((string) $table))->fetch(PDO::FETCH_ASSOC);
    $ddl = (string) ($row['Create Table'] ?? '');

    // Normalise so diffs stay small across environments:
    //  - drop AUTO_INCREMENT counter
    //  - CREATE TABLE IF NOT EXISTS for idempotent re-import
    $ddl = preg_replace('/ AUTO_INCREMENT=\d+/', '', $ddl) ?? $ddl;
    $ddl = preg_replace('/^CREATE TABLE /', 'CREATE TABLE IF NOT EXISTS ', $ddl) ?? $ddl;

    $out[] = "-- ---------------------------------------------------------------------";
    $out[] = "-- {$table}";
    $out[] = "-- ---------------------------------------------------------------------";
    $out[] = "DROP TABLE IF EXISTS " . $db->quoteIdent((string) $table) . ";";
    $out[] = $ddl . ";";
    $out[] = "";
}

$out[] = "SET FOREIGN_KEY_CHECKS = 1;";
$out[] = "";

$target = dirname(__DIR__) . '/database/schema.sql';
file_put_contents($target, implode("\n", $out));

fwrite(STDOUT, "Wrote " . count($tables) . " tables to database/schema.sql\n");
