-- =====================================================================
-- AgriVault — consolidated database schema (generated)
--
-- Generated by database/dump_schema.php from the applied migrations in
-- database/schema/. Do not edit by hand: change a migration and re-run.
--
-- Fresh install in one shot:
--   mysql -u USER -p DBNAME < database/schema.sql
--   then: INSERT the database/seed/*.sql files.
-- =====================================================================

SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- ---------------------------------------------------------------------
-- admin_users
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `admin_users`;
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` varchar(40) NOT NULL,
  `email` varchar(190) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(120) NOT NULL,
  `is_super_admin` tinyint(1) NOT NULL DEFAULT 0,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_admin_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- audit_log
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` varchar(40) NOT NULL,
  `actor_type` enum('user','admin','system') NOT NULL DEFAULT 'system',
  `actor_id` varchar(40) DEFAULT NULL,
  `action` varchar(80) NOT NULL,
  `target_type` varchar(60) DEFAULT NULL,
  `target_id` varchar(40) DEFAULT NULL,
  `farm_id` varchar(40) DEFAULT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `meta` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta`)),
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_farm` (`farm_id`),
  KEY `idx_audit_actor` (`actor_id`),
  KEY `idx_audit_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- auth_tokens
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `auth_tokens`;
CREATE TABLE IF NOT EXISTS `auth_tokens` (
  `id` varchar(40) NOT NULL,
  `user_id` varchar(40) NOT NULL,
  `type` enum('activation','reset') NOT NULL,
  `token_hash` char(64) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_auth_tokens_hash` (`token_hash`),
  KEY `idx_auth_tokens_user_type` (`user_id`,`type`),
  CONSTRAINT `fk_auth_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- farms
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `farms`;
CREATE TABLE IF NOT EXISTS `farms` (
  `id` varchar(40) NOT NULL,
  `name` varchar(160) NOT NULL,
  `location` varchar(160) NOT NULL DEFAULT '',
  `location_lat` double DEFAULT NULL,
  `location_lng` double DEFAULT NULL,
  `owner_name` varchar(120) DEFAULT NULL,
  `user_id` varchar(40) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_farms_user` (`user_id`),
  CONSTRAINT `fk_farms_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- farm_members
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `farm_members`;
CREATE TABLE IF NOT EXISTS `farm_members` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `user_id` varchar(40) DEFAULT NULL,
  `role` varchar(20) NOT NULL,
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`permissions`)),
  `invite_email` varchar(190) DEFAULT NULL,
  `invite_token` char(64) DEFAULT NULL,
  `invite_expires_at` datetime DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `invited_by` varchar(40) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_member_farm_user` (`farm_id`,`user_id`),
  UNIQUE KEY `uniq_member_invite_token` (`invite_token`),
  KEY `idx_member_user` (`user_id`),
  KEY `idx_member_farm` (`farm_id`),
  CONSTRAINT `fk_member_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_member_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- mail_queue
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `mail_queue`;
CREATE TABLE IF NOT EXISTS `mail_queue` (
  `id` varchar(40) NOT NULL,
  `to_email` varchar(190) NOT NULL,
  `to_name` varchar(120) DEFAULT NULL,
  `subject` varchar(255) NOT NULL,
  `html_body` mediumtext NOT NULL,
  `text_body` mediumtext NOT NULL,
  `status` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `last_error` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `sent_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mail_queue_status` (`status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `payments`;
CREATE TABLE IF NOT EXISTS `payments` (
  `id` varchar(40) NOT NULL,
  `subscription_id` varchar(40) NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'MWK',
  `status` varchar(20) NOT NULL,
  `method` varchar(30) NOT NULL,
  `reference` varchar(120) DEFAULT NULL,
  `provider_transaction_id` varchar(120) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `created_by_admin_id` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_payments_provider_txn` (`provider_transaction_id`),
  KEY `idx_payments_subscription` (`subscription_id`),
  CONSTRAINT `fk_payments_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- rate_limits
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `rate_limits`;
CREATE TABLE IF NOT EXISTS `rate_limits` (
  `bucket` varchar(64) NOT NULL,
  `attempts` int(10) unsigned NOT NULL DEFAULT 0,
  `expires_at` int(10) unsigned NOT NULL,
  PRIMARY KEY (`bucket`),
  KEY `idx_rate_limits_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `sessions`;
CREATE TABLE IF NOT EXISTS `sessions` (
  `id` varchar(64) NOT NULL,
  `user_id` varchar(40) DEFAULT NULL,
  `admin_id` varchar(40) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `payload` mediumtext NOT NULL,
  `last_activity` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sessions_last_activity` (`last_activity`),
  KEY `idx_sessions_user` (`user_id`),
  KEY `idx_sessions_admin` (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- subscriptions
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `subscriptions`;
CREATE TABLE IF NOT EXISTS `subscriptions` (
  `id` varchar(40) NOT NULL,
  `user_id` varchar(40) NOT NULL,
  `tier_id` varchar(40) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `billing_cycle` varchar(20) NOT NULL DEFAULT 'monthly',
  `start_date` datetime NOT NULL,
  `end_date` datetime DEFAULT NULL,
  `trial_ends_at` datetime DEFAULT NULL,
  `provider` varchar(20) DEFAULT NULL,
  `provider_subscription_id` varchar(120) DEFAULT NULL,
  `activation_token` varchar(80) DEFAULT NULL,
  `activated_at` datetime DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_subscriptions_user` (`user_id`),
  UNIQUE KEY `uniq_subscriptions_provider` (`provider_subscription_id`),
  UNIQUE KEY `uniq_subscriptions_acttoken` (`activation_token`),
  KEY `idx_subscriptions_tier` (`tier_id`),
  CONSTRAINT `fk_subscriptions_tier` FOREIGN KEY (`tier_id`) REFERENCES `subscription_tiers` (`id`),
  CONSTRAINT `fk_subscriptions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- subscription_tiers
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `subscription_tiers`;
CREATE TABLE IF NOT EXISTS `subscription_tiers` (
  `id` varchar(40) NOT NULL,
  `name` varchar(80) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `currency` varchar(3) NOT NULL DEFAULT 'MWK',
  `price_monthly` decimal(12,2) NOT NULL DEFAULT 0.00,
  `price_annual` decimal(12,2) DEFAULT NULL,
  `price_lifetime` decimal(12,2) DEFAULT NULL,
  `audience` varchar(120) DEFAULT NULL,
  `cta_label` varchar(80) DEFAULT NULL,
  `cta_href` varchar(255) DEFAULT NULL,
  `offer_items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`offer_items`)),
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_public` tinyint(1) NOT NULL DEFAULT 1,
  `is_featured` tinyint(1) NOT NULL DEFAULT 0,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `max_fields` int(11) NOT NULL DEFAULT 1,
  `max_crops` int(11) NOT NULL DEFAULT 1,
  `max_activities` int(11) NOT NULL DEFAULT 10,
  `max_transactions` int(11) NOT NULL DEFAULT 5,
  `max_employees` int(11) NOT NULL DEFAULT 1,
  `max_farms` int(11) NOT NULL DEFAULT 1,
  `max_team_members` int(11) NOT NULL DEFAULT 1,
  `season_analytics` tinyint(1) NOT NULL DEFAULT 0,
  `yield_suggestions` tinyint(1) NOT NULL DEFAULT 0,
  `cost_per_hectare` tinyint(1) NOT NULL DEFAULT 0,
  `payroll_tracking` tinyint(1) NOT NULL DEFAULT 0,
  `multiple_farms` tinyint(1) NOT NULL DEFAULT 0,
  `team_accounts` tinyint(1) NOT NULL DEFAULT 0,
  `custom_reports` tinyint(1) NOT NULL DEFAULT 0,
  `api_access` tinyint(1) NOT NULL DEFAULT 0,
  `data_retention_lifetime` tinyint(1) NOT NULL DEFAULT 1,
  `sync_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tiers_visible` (`is_active`,`is_public`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` varchar(40) NOT NULL,
  `name` varchar(120) DEFAULT NULL,
  `email` varchar(190) NOT NULL,
  `password` varchar(255) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 0,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- _migrations
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `_migrations`;
CREATE TABLE IF NOT EXISTS `_migrations` (
  `filename` varchar(191) NOT NULL,
  `applied_at` datetime NOT NULL,
  PRIMARY KEY (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
