-- =====================================================================
-- AgriVault — consolidated database schema (generated)
--
-- Generated by database/dump_schema.php from the applied migrations in
-- database/schema/. Do not edit by hand: change a migration and re-run.
--
-- Fresh install in one shot:
--   mysql -u USER -p DBNAME < database/schema.sql
--   then: INSERT the database/seed/*.sql files.
-- =====================================================================

SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- ---------------------------------------------------------------------
-- activity_inputs
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `activity_inputs`;
CREATE TABLE IF NOT EXISTS `activity_inputs` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `activity_id` varchar(40) NOT NULL,
  `input_name` varchar(160) NOT NULL,
  `category` varchar(60) NOT NULL DEFAULT 'Other',
  `quantity` decimal(12,3) NOT NULL DEFAULT 0.000,
  `unit` varchar(20) NOT NULL DEFAULT '',
  `unit_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `acquisition_unit_cost` decimal(12,2) DEFAULT NULL,
  `time_value_cost` decimal(12,2) DEFAULT NULL,
  `inventory_item_id` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_activity` (`activity_id`),
  KEY `idx_ai_farm` (`farm_id`),
  KEY `idx_ai_inventory` (`inventory_item_id`),
  CONSTRAINT `fk_ai_activity` FOREIGN KEY (`activity_id`) REFERENCES `farm_activities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ai_inventory` FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- activity_labour
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `activity_labour`;
CREATE TABLE IF NOT EXISTS `activity_labour` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `activity_id` varchar(40) NOT NULL,
  `employee_id` varchar(40) DEFAULT NULL,
  `worker_name` varchar(120) DEFAULT NULL,
  `hours_worked` decimal(8,2) NOT NULL DEFAULT 0.00,
  `days_worked` decimal(8,2) NOT NULL DEFAULT 0.00,
  `total_cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_al_activity` (`activity_id`),
  KEY `idx_al_farm` (`farm_id`),
  KEY `fk_al_employee` (`employee_id`),
  CONSTRAINT `fk_al_activity` FOREIGN KEY (`activity_id`) REFERENCES `farm_activities` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_al_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- activity_other_costs
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `activity_other_costs`;
CREATE TABLE IF NOT EXISTS `activity_other_costs` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `activity_id` varchar(40) NOT NULL,
  `description` varchar(200) NOT NULL,
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  KEY `idx_aoc_activity` (`activity_id`),
  KEY `idx_aoc_farm` (`farm_id`),
  CONSTRAINT `fk_aoc_activity` FOREIGN KEY (`activity_id`) REFERENCES `farm_activities` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- admin_users
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `admin_users`;
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` varchar(40) NOT NULL,
  `email` varchar(190) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(120) NOT NULL,
  `is_super_admin` tinyint(1) NOT NULL DEFAULT 0,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_admin_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- animals
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `animals`;
CREATE TABLE IF NOT EXISTS `animals` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `livestock_type_id` varchar(40) NOT NULL,
  `tag` varchar(60) DEFAULT NULL,
  `name` varchar(80) DEFAULT NULL,
  `animal_group` varchar(80) DEFAULT NULL,
  `sex` varchar(10) NOT NULL DEFAULT 'Unknown',
  `birth_date` date DEFAULT NULL,
  `acquisition_date` date NOT NULL,
  `acquisition_type` varchar(40) NOT NULL DEFAULT 'Born on farm',
  `acquisition_cost` decimal(12,2) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'Active',
  `breed` varchar(80) DEFAULT NULL,
  `colour` varchar(60) DEFAULT NULL,
  `weight` decimal(10,2) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `parent_id` varchar(40) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_animals_farm` (`farm_id`,`status`),
  KEY `idx_animals_type` (`livestock_type_id`),
  KEY `idx_animals_parent` (`parent_id`),
  CONSTRAINT `fk_animals_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_animals_parent` FOREIGN KEY (`parent_id`) REFERENCES `animals` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_animals_type` FOREIGN KEY (`livestock_type_id`) REFERENCES `livestock_types` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- animal_expenses
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `animal_expenses`;
CREATE TABLE IF NOT EXISTS `animal_expenses` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `animal_id` varchar(40) DEFAULT NULL,
  `category` varchar(60) NOT NULL DEFAULT 'Other',
  `description` varchar(200) NOT NULL,
  `amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `date` date NOT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ae_farm_date` (`farm_id`,`date`),
  KEY `idx_ae_animal` (`animal_id`),
  CONSTRAINT `fk_ae_animal` FOREIGN KEY (`animal_id`) REFERENCES `animals` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_ae_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- animal_health
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `animal_health`;
CREATE TABLE IF NOT EXISTS `animal_health` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `animal_id` varchar(40) NOT NULL,
  `type` varchar(60) NOT NULL,
  `description` varchar(255) NOT NULL,
  `veterinarian` varchar(120) DEFAULT NULL,
  `cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `date` date NOT NULL,
  `next_due_date` date DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ah_animal` (`animal_id`),
  KEY `idx_ah_farm` (`farm_id`),
  CONSTRAINT `fk_ah_animal` FOREIGN KEY (`animal_id`) REFERENCES `animals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- animal_production
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `animal_production`;
CREATE TABLE IF NOT EXISTS `animal_production` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `animal_id` varchar(40) DEFAULT NULL,
  `type` varchar(60) NOT NULL,
  `quantity` decimal(14,3) NOT NULL DEFAULT 0.000,
  `unit` varchar(20) NOT NULL DEFAULT '',
  `date` date NOT NULL,
  `price_per_unit` decimal(12,2) DEFAULT NULL,
  `total_value` decimal(14,2) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ap_animal` (`animal_id`),
  KEY `idx_ap_farm_date` (`farm_id`,`date`),
  CONSTRAINT `fk_ap_animal` FOREIGN KEY (`animal_id`) REFERENCES `animals` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ap_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- animal_sales
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `animal_sales`;
CREATE TABLE IF NOT EXISTS `animal_sales` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `animal_id` varchar(40) NOT NULL,
  `transaction_id` varchar(40) DEFAULT NULL,
  `sale_date` date NOT NULL,
  `quantity` int(11) NOT NULL DEFAULT 1,
  `weight_at_sale` decimal(10,2) DEFAULT NULL,
  `price_per_kg` decimal(12,2) DEFAULT NULL,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `buyer` varchar(160) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_as_farm` (`farm_id`),
  KEY `idx_as_animal` (`animal_id`),
  KEY `fk_as_tx` (`transaction_id`),
  CONSTRAINT `fk_as_animal` FOREIGN KEY (`animal_id`) REFERENCES `animals` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_as_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_as_tx` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- animal_weight
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `animal_weight`;
CREATE TABLE IF NOT EXISTS `animal_weight` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `animal_id` varchar(40) NOT NULL,
  `weight` decimal(10,2) NOT NULL DEFAULT 0.00,
  `unit` varchar(10) NOT NULL DEFAULT 'kg',
  `date` date NOT NULL,
  `notes` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_aw_animal` (`animal_id`,`date`),
  CONSTRAINT `fk_aw_animal` FOREIGN KEY (`animal_id`) REFERENCES `animals` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- audit_log
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` varchar(40) NOT NULL,
  `actor_type` enum('user','admin','system') NOT NULL DEFAULT 'system',
  `actor_id` varchar(40) DEFAULT NULL,
  `action` varchar(80) NOT NULL,
  `target_type` varchar(60) DEFAULT NULL,
  `target_id` varchar(40) DEFAULT NULL,
  `farm_id` varchar(40) DEFAULT NULL,
  `ip` varchar(45) DEFAULT NULL,
  `meta` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`meta`)),
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_farm` (`farm_id`),
  KEY `idx_audit_actor` (`actor_id`),
  KEY `idx_audit_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- auth_tokens
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `auth_tokens`;
CREATE TABLE IF NOT EXISTS `auth_tokens` (
  `id` varchar(40) NOT NULL,
  `user_id` varchar(40) NOT NULL,
  `type` enum('activation','reset') NOT NULL,
  `token_hash` char(64) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_auth_tokens_hash` (`token_hash`),
  KEY `idx_auth_tokens_user_type` (`user_id`,`type`),
  CONSTRAINT `fk_auth_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- crop_fields
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `crop_fields`;
CREATE TABLE IF NOT EXISTS `crop_fields` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `field_id` varchar(40) NOT NULL,
  `crop_type_id` varchar(40) NOT NULL,
  `variety` varchar(120) NOT NULL DEFAULT '',
  `area_planted` decimal(12,3) NOT NULL DEFAULT 0.000,
  `season` varchar(60) NOT NULL DEFAULT '',
  `planting_date` date NOT NULL,
  `expected_harvest_date` date NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'Active',
  `is_archived` tinyint(1) NOT NULL DEFAULT 0,
  `archived_at` datetime DEFAULT NULL,
  `archived_reason` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cf_farm` (`farm_id`),
  KEY `idx_cf_field` (`field_id`),
  KEY `idx_cf_crop_type` (`crop_type_id`),
  KEY `idx_cf_season` (`farm_id`,`season`),
  KEY `idx_cf_active` (`farm_id`,`is_archived`,`status`),
  CONSTRAINT `fk_cf_crop_type` FOREIGN KEY (`crop_type_id`) REFERENCES `crop_types` (`id`),
  CONSTRAINT `fk_cf_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cf_field` FOREIGN KEY (`field_id`) REFERENCES `fields` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- crop_types
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `crop_types`;
CREATE TABLE IF NOT EXISTS `crop_types` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) DEFAULT NULL,
  `name` varchar(120) NOT NULL,
  `is_custom` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_crop_types_scope_name` (`farm_id`,`name`),
  KEY `idx_crop_types_farm` (`farm_id`),
  CONSTRAINT `fk_crop_types_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- employees
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `employees`;
CREATE TABLE IF NOT EXISTS `employees` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `name` varchar(120) NOT NULL,
  `role` varchar(80) NOT NULL DEFAULT '',
  `pay_rate` decimal(12,2) NOT NULL DEFAULT 0.00,
  `pay_rate_unit` varchar(20) NOT NULL DEFAULT 'day',
  `phone` varchar(40) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_employees_farm` (`farm_id`,`is_active`),
  CONSTRAINT `fk_employees_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- farms
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `farms`;
CREATE TABLE IF NOT EXISTS `farms` (
  `id` varchar(40) NOT NULL,
  `name` varchar(160) NOT NULL,
  `location` varchar(160) NOT NULL DEFAULT '',
  `location_lat` double DEFAULT NULL,
  `location_lng` double DEFAULT NULL,
  `owner_name` varchar(120) DEFAULT NULL,
  `user_id` varchar(40) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_farms_user` (`user_id`),
  CONSTRAINT `fk_farms_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- farm_activities
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `farm_activities`;
CREATE TABLE IF NOT EXISTS `farm_activities` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `field_id` varchar(40) NOT NULL,
  `crop_field_id` varchar(40) DEFAULT NULL,
  `activity_type` varchar(80) NOT NULL,
  `date` date NOT NULL,
  `notes` text DEFAULT NULL,
  `responsible_person_name` varchar(120) DEFAULT NULL,
  `responsible_employee_id` varchar(40) DEFAULT NULL,
  `created_by_id` varchar(40) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fa_farm_date` (`farm_id`,`date`),
  KEY `idx_fa_field` (`field_id`),
  KEY `idx_fa_crop_field` (`crop_field_id`),
  KEY `idx_fa_type` (`farm_id`,`activity_type`),
  KEY `fk_fa_employee` (`responsible_employee_id`),
  KEY `fk_fa_creator` (`created_by_id`),
  CONSTRAINT `fk_fa_creator` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_fa_crop_field` FOREIGN KEY (`crop_field_id`) REFERENCES `crop_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fa_employee` FOREIGN KEY (`responsible_employee_id`) REFERENCES `employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fa_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_fa_field` FOREIGN KEY (`field_id`) REFERENCES `fields` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- farm_credit_scores
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `farm_credit_scores`;
CREATE TABLE IF NOT EXISTS `farm_credit_scores` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `user_id` varchar(40) NOT NULL,
  `score` int(11) NOT NULL,
  `grade` varchar(4) NOT NULL,
  `factors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`factors`)),
  `generated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fcs_farm` (`farm_id`,`generated_at`),
  KEY `fk_fcs_user` (`user_id`),
  CONSTRAINT `fk_fcs_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_fcs_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- farm_markers
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `farm_markers`;
CREATE TABLE IF NOT EXISTS `farm_markers` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `field_id` varchar(40) DEFAULT NULL,
  `type` varchar(30) NOT NULL DEFAULT 'other',
  `label` varchar(120) NOT NULL,
  `lat` double NOT NULL,
  `lng` double NOT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `icon` varchar(40) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_marker_farm` (`farm_id`),
  KEY `fk_marker_field` (`field_id`),
  CONSTRAINT `fk_marker_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_marker_field` FOREIGN KEY (`field_id`) REFERENCES `fields` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- farm_members
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `farm_members`;
CREATE TABLE IF NOT EXISTS `farm_members` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `user_id` varchar(40) DEFAULT NULL,
  `role` varchar(20) NOT NULL,
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`permissions`)),
  `invite_email` varchar(190) DEFAULT NULL,
  `invite_token` char(64) DEFAULT NULL,
  `invite_expires_at` datetime DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `invited_by` varchar(40) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_member_farm_user` (`farm_id`,`user_id`),
  UNIQUE KEY `uniq_member_invite_token` (`invite_token`),
  KEY `idx_member_user` (`user_id`),
  KEY `idx_member_farm` (`farm_id`),
  CONSTRAINT `fk_member_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_member_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- fields
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `fields`;
CREATE TABLE IF NOT EXISTS `fields` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `name` varchar(160) NOT NULL,
  `total_area` decimal(12,3) NOT NULL DEFAULT 0.000,
  `cultivatable_area` decimal(12,3) NOT NULL DEFAULT 0.000,
  `soil_type` varchar(80) NOT NULL DEFAULT '',
  `location_lat` double DEFAULT NULL,
  `location_lng` double DEFAULT NULL,
  `boundary_points` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`boundary_points`)),
  `notes` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fields_farm` (`farm_id`),
  CONSTRAINT `fk_fields_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- field_boundaries
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `field_boundaries`;
CREATE TABLE IF NOT EXISTS `field_boundaries` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `field_id` varchar(40) NOT NULL,
  `geo_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`geo_json`)),
  `area_ha` decimal(12,4) DEFAULT NULL,
  `centroid_lat` double DEFAULT NULL,
  `centroid_lng` double DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_boundary_field` (`field_id`),
  KEY `idx_boundary_farm` (`farm_id`),
  CONSTRAINT `fk_boundary_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_boundary_field` FOREIGN KEY (`field_id`) REFERENCES `fields` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- field_zones
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `field_zones`;
CREATE TABLE IF NOT EXISTS `field_zones` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `boundary_id` varchar(40) NOT NULL,
  `field_id` varchar(40) NOT NULL,
  `crop_field_id` varchar(40) DEFAULT NULL,
  `name` varchar(120) NOT NULL,
  `type` varchar(40) NOT NULL DEFAULT 'management',
  `geo_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`geo_json`)),
  `area_ha` decimal(12,4) DEFAULT NULL,
  `colour` varchar(20) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_zone_boundary` (`boundary_id`),
  KEY `idx_zone_field` (`field_id`),
  KEY `idx_zone_farm` (`farm_id`),
  KEY `fk_zone_crop_field` (`crop_field_id`),
  CONSTRAINT `fk_zone_boundary` FOREIGN KEY (`boundary_id`) REFERENCES `field_boundaries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_zone_crop_field` FOREIGN KEY (`crop_field_id`) REFERENCES `crop_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_zone_field` FOREIGN KEY (`field_id`) REFERENCES `fields` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- harvest_yields
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `harvest_yields`;
CREATE TABLE IF NOT EXISTS `harvest_yields` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `crop_field_id` varchar(40) NOT NULL,
  `harvest_date` date NOT NULL,
  `quantity` decimal(14,3) NOT NULL DEFAULT 0.000,
  `unit` varchar(20) NOT NULL DEFAULT 'kg',
  `unit_weight` decimal(10,3) DEFAULT NULL,
  `quantity_kg` decimal(14,3) NOT NULL DEFAULT 0.000,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hy_farm` (`farm_id`),
  KEY `idx_hy_crop_field` (`crop_field_id`),
  CONSTRAINT `fk_hy_crop_field` FOREIGN KEY (`crop_field_id`) REFERENCES `crop_fields` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hy_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- inventory_items
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `inventory_items`;
CREATE TABLE IF NOT EXISTS `inventory_items` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `name` varchar(160) NOT NULL,
  `category` varchar(40) NOT NULL DEFAULT 'other',
  `unit` varchar(20) NOT NULL DEFAULT 'kg',
  `quantity` decimal(14,3) NOT NULL DEFAULT 0.000,
  `acquisition_unit_cost` decimal(12,2) DEFAULT NULL,
  `acquired_at` date DEFAULT NULL,
  `unit_weight` decimal(10,3) DEFAULT NULL,
  `season` varchar(60) DEFAULT NULL,
  `crop_field_id` varchar(40) DEFAULT NULL,
  `harvest_yield_id` varchar(40) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_inv_farm` (`farm_id`,`category`),
  KEY `idx_inv_crop_field` (`crop_field_id`),
  KEY `fk_inv_yield` (`harvest_yield_id`),
  CONSTRAINT `fk_inv_crop_field` FOREIGN KEY (`crop_field_id`) REFERENCES `crop_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_inv_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_inv_yield` FOREIGN KEY (`harvest_yield_id`) REFERENCES `harvest_yields` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- inventory_sales
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `inventory_sales`;
CREATE TABLE IF NOT EXISTS `inventory_sales` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `inventory_item_id` varchar(40) NOT NULL,
  `transaction_id` varchar(40) DEFAULT NULL,
  `quantity_sold` decimal(14,3) NOT NULL DEFAULT 0.000,
  `unit` varchar(20) NOT NULL DEFAULT '',
  `price_per_unit` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `buyer_name` varchar(160) DEFAULT NULL,
  `sale_date` date NOT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_invs_farm` (`farm_id`),
  KEY `idx_invs_item` (`inventory_item_id`),
  KEY `fk_invs_tx` (`transaction_id`),
  CONSTRAINT `fk_invs_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_invs_item` FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_invs_tx` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- livestock_types
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `livestock_types`;
CREATE TABLE IF NOT EXISTS `livestock_types` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `name` varchar(80) NOT NULL,
  `category` varchar(60) NOT NULL DEFAULT '',
  `icon` varchar(40) NOT NULL DEFAULT 'cow',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_lt_farm_name` (`farm_id`,`name`),
  CONSTRAINT `fk_lt_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- mail_queue
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `mail_queue`;
CREATE TABLE IF NOT EXISTS `mail_queue` (
  `id` varchar(40) NOT NULL,
  `to_email` varchar(190) NOT NULL,
  `to_name` varchar(120) DEFAULT NULL,
  `subject` varchar(255) NOT NULL,
  `html_body` mediumtext NOT NULL,
  `text_body` mediumtext NOT NULL,
  `status` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `last_error` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `sent_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mail_queue_status` (`status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- overhead_expenses
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `overhead_expenses`;
CREATE TABLE IF NOT EXISTS `overhead_expenses` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `description` varchar(200) NOT NULL,
  `category` varchar(40) NOT NULL DEFAULT 'Other',
  `amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `date` date NOT NULL,
  `recurring` tinyint(1) NOT NULL DEFAULT 0,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_oh_farm_date` (`farm_id`,`date`),
  CONSTRAINT `fk_oh_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `payments`;
CREATE TABLE IF NOT EXISTS `payments` (
  `id` varchar(40) NOT NULL,
  `subscription_id` varchar(40) NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'MWK',
  `status` varchar(20) NOT NULL,
  `method` varchar(30) NOT NULL,
  `reference` varchar(120) DEFAULT NULL,
  `provider_transaction_id` varchar(120) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `created_by_admin_id` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_payments_provider_txn` (`provider_transaction_id`),
  KEY `idx_payments_subscription` (`subscription_id`),
  CONSTRAINT `fk_payments_subscription` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- rate_limits
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `rate_limits`;
CREATE TABLE IF NOT EXISTS `rate_limits` (
  `bucket` varchar(64) NOT NULL,
  `attempts` int(10) unsigned NOT NULL DEFAULT 0,
  `expires_at` int(10) unsigned NOT NULL,
  PRIMARY KEY (`bucket`),
  KEY `idx_rate_limits_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- saved_reports
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `saved_reports`;
CREATE TABLE IF NOT EXISTS `saved_reports` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `user_id` varchar(40) NOT NULL,
  `name` varchar(120) NOT NULL,
  `config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`config`)),
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sr_farm` (`farm_id`),
  KEY `fk_sr_user` (`user_id`),
  CONSTRAINT `fk_sr_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sr_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `sessions`;
CREATE TABLE IF NOT EXISTS `sessions` (
  `id` varchar(64) NOT NULL,
  `user_id` varchar(40) DEFAULT NULL,
  `admin_id` varchar(40) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `payload` mediumtext NOT NULL,
  `last_activity` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sessions_last_activity` (`last_activity`),
  KEY `idx_sessions_user` (`user_id`),
  KEY `idx_sessions_admin` (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- subscriptions
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `subscriptions`;
CREATE TABLE IF NOT EXISTS `subscriptions` (
  `id` varchar(40) NOT NULL,
  `user_id` varchar(40) NOT NULL,
  `tier_id` varchar(40) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `billing_cycle` varchar(20) NOT NULL DEFAULT 'monthly',
  `start_date` datetime NOT NULL,
  `end_date` datetime DEFAULT NULL,
  `trial_ends_at` datetime DEFAULT NULL,
  `provider` varchar(20) DEFAULT NULL,
  `provider_subscription_id` varchar(120) DEFAULT NULL,
  `activation_token` varchar(80) DEFAULT NULL,
  `activated_at` datetime DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_subscriptions_user` (`user_id`),
  UNIQUE KEY `uniq_subscriptions_provider` (`provider_subscription_id`),
  UNIQUE KEY `uniq_subscriptions_acttoken` (`activation_token`),
  KEY `idx_subscriptions_tier` (`tier_id`),
  CONSTRAINT `fk_subscriptions_tier` FOREIGN KEY (`tier_id`) REFERENCES `subscription_tiers` (`id`),
  CONSTRAINT `fk_subscriptions_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- subscription_tiers
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `subscription_tiers`;
CREATE TABLE IF NOT EXISTS `subscription_tiers` (
  `id` varchar(40) NOT NULL,
  `name` varchar(80) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `currency` varchar(3) NOT NULL DEFAULT 'MWK',
  `price_monthly` decimal(12,2) NOT NULL DEFAULT 0.00,
  `price_annual` decimal(12,2) DEFAULT NULL,
  `price_lifetime` decimal(12,2) DEFAULT NULL,
  `audience` varchar(120) DEFAULT NULL,
  `cta_label` varchar(80) DEFAULT NULL,
  `cta_href` varchar(255) DEFAULT NULL,
  `offer_items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`offer_items`)),
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_public` tinyint(1) NOT NULL DEFAULT 1,
  `is_featured` tinyint(1) NOT NULL DEFAULT 0,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `max_fields` int(11) NOT NULL DEFAULT 1,
  `max_crops` int(11) NOT NULL DEFAULT 1,
  `max_activities` int(11) NOT NULL DEFAULT 10,
  `max_transactions` int(11) NOT NULL DEFAULT 5,
  `max_employees` int(11) NOT NULL DEFAULT 1,
  `max_farms` int(11) NOT NULL DEFAULT 1,
  `max_team_members` int(11) NOT NULL DEFAULT 1,
  `season_analytics` tinyint(1) NOT NULL DEFAULT 0,
  `yield_suggestions` tinyint(1) NOT NULL DEFAULT 0,
  `cost_per_hectare` tinyint(1) NOT NULL DEFAULT 0,
  `payroll_tracking` tinyint(1) NOT NULL DEFAULT 0,
  `multiple_farms` tinyint(1) NOT NULL DEFAULT 0,
  `team_accounts` tinyint(1) NOT NULL DEFAULT 0,
  `custom_reports` tinyint(1) NOT NULL DEFAULT 0,
  `api_access` tinyint(1) NOT NULL DEFAULT 0,
  `data_retention_lifetime` tinyint(1) NOT NULL DEFAULT 1,
  `sync_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tiers_visible` (`is_active`,`is_public`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- transactions
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `transactions`;
CREATE TABLE IF NOT EXISTS `transactions` (
  `id` varchar(40) NOT NULL,
  `farm_id` varchar(40) NOT NULL,
  `type` varchar(10) NOT NULL,
  `category` varchar(80) NOT NULL DEFAULT 'Other',
  `amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `date` date NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `season` varchar(60) DEFAULT NULL,
  `field_id` varchar(40) DEFAULT NULL,
  `crop_field_id` varchar(40) DEFAULT NULL,
  `harvest_yield_id` varchar(40) DEFAULT NULL,
  `inventory_item_id` varchar(40) DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'manual',
  `created_by_id` varchar(40) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tx_farm_date` (`farm_id`,`date`),
  KEY `idx_tx_farm_type` (`farm_id`,`type`),
  KEY `idx_tx_season` (`farm_id`,`season`),
  KEY `idx_tx_crop_field` (`crop_field_id`),
  KEY `fk_tx_field` (`field_id`),
  KEY `fk_tx_yield` (`harvest_yield_id`),
  KEY `fk_tx_creator` (`created_by_id`),
  KEY `fk_tx_inventory` (`inventory_item_id`),
  CONSTRAINT `fk_tx_creator` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_tx_crop_field` FOREIGN KEY (`crop_field_id`) REFERENCES `crop_fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tx_farm` FOREIGN KEY (`farm_id`) REFERENCES `farms` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_tx_field` FOREIGN KEY (`field_id`) REFERENCES `fields` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tx_inventory` FOREIGN KEY (`inventory_item_id`) REFERENCES `inventory_items` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_tx_yield` FOREIGN KEY (`harvest_yield_id`) REFERENCES `harvest_yields` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` varchar(40) NOT NULL,
  `name` varchar(120) DEFAULT NULL,
  `email` varchar(190) NOT NULL,
  `password` varchar(255) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 0,
  `last_login_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- _migrations
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS `_migrations`;
CREATE TABLE IF NOT EXISTS `_migrations` (
  `filename` varchar(191) NOT NULL,
  `applied_at` datetime NOT NULL,
  PRIMARY KEY (`filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
